### ISSUE TITLE
Doesn't work with 2.9

### ISSUE THREAD

**Issue by ninetalescommander** [Artmann/blender-batch-fbx-exporter#3]
I've downloaded this but it keeps telling me to upgrade to 2.8. Can we get a fix?

**Comment by dasparadoxon** [comment]
Its not working cause it needs to be an _init_.py file. I did that, but then it has no entry anywhere, so I looked that up after activation, I will fork this here someday and do that, but for now just use : 

import bpy

objects = bpy.context.selected_objects

for obj in objects:
    bpy.ops.object.select_all(action='DESELECT')
    path = bpy.path.abspath("//" + obj.name + ".fbx")
    obj.select_set(True)
    bpy.ops.export_scene.fbx(filepath=path, use_selection=True)  

in a script window inside blender and press the execute button and it will export all selected meshes.

Thanks to  Artman, that was exactly what I was looking for !!!

**Comment by Artmann** [comment]
I just made an update to make the addon show up in the context menu for version 2.91.2. Can you check if you still experience the problem with the latest version?
