### ISSUE TITLE
Please update to Blender 3.x!

### ISSUE THREAD

**Issue by BSBMteam** [Artmann/blender-batch-fbx-exporter#4]
I tried to install this, but no tab pops up on the right

**Comment by Artmann** [comment]
I'm using this with Blender 3.2.1. At with stage are you encountering a problem?

**Comment by BSBMteam** [comment]
I'm in Blender 3.5.

When I try to install the .zip file or the python file, it shows up in the Edit > Preferences > Add-ons tab, but I cannot see the tab for it on the right in the sidebar, but maybe it worked

Is it called "Object: Batch FBX Exporter?"  

If so, maybe I had to dig thru my add-ons and it works

**Comment by Artmann** [comment]
That's the right one :)
